# Generated by Django 4.2.6 on 2023-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
